eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EDUCATION_EUREKA_SERVER:http://localhost:1337/eureka/}
    # improve refresh time
    registryFetchIntervalSeconds: 5
  # improve refresh time
  instance.leaseRenewalIntervalInSeconds: 5
  server.response-cache-update-interval-ms: 1000
link:
    expiration: 3600  
jwt:
    expiration: 3000
    header: Authorization
    issuer: holter.io
    prefix: Bearer
    route:
      authentication:
        create: /sandeep
        refresh: /refresh
    secret: my^hol67TR
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/holter?autoReconnect=true&serverTimezone=UTC&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: sandeep
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
  main.allow-bean-definition-overriding: true
holter:
  apigateway:
    url: localhost:8090
  username: admin
  password: sandeep
cardio:
  config:
    aws:
      region: ap-south-1
      accessKey: ENC(5LPEc5Qt/h/WhX9g01UgvRyPmd+MxQzT2MletVYQ02U=)
      secretKey: ENC(n4pwMuEvx97LgwfHl6FyKKGj4H9YVgtJvmHw8qXFrvJyv/19GKHMDij/CJqPBYr2wsUwlKYhI48=)
    
    bucket: cardio-dev-assets
jasypt:
 encryptor:
  password: Cardio-Secret-!290Dev
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

bitrhythm:
 username: Mediprimeadmin
 password: PrimeKav@686868ieieie
 
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 90000
